<?php

return array(
  'tableName' => 'usuarios',
  'engine' => 'InnoDB',
  'charset' => 'utf8',
  'collation' => 'utf8_unicode_ci',
  'fields' => array(
    'id_user' => array(
      'name' => 'id_user',
      'type' => 'int',
      'pk' => false,
      'allowNull' => false,
      'unsigned' => true,
      'zerofill' => false,
      'autoIncrement' => true,
      'len' => 4,
    ),
    'name' => array(
      'name' => 'name',
      'type' => 'varchar',
      'pk' => false,
      'allowNull' => true,
      'collation' => 'utf8_unicode_ci',
      'charset' => 'utf8',
      'len' => '128',
    ),
    'email' => array(
      'name' => 'email',
      'type' => 'varchar',
      'pk' => false,
      'allowNull' => true,
      'collation' => 'utf8_unicode_ci',
      'charset' => 'utf8',
      'len' => '128',
    ),
    'sueldo' => array(
      'name' => 'sueldo',
      'type' => 'float',
      'pk' => false,
      'allowNull' => true,
      'unsigned' => false,
      'zerofill' => false,
      'autoIncrement' => false,
      'precision' => '10',
      'scale' => '0',
      'len' => 0,
    ),
    'created_at' => array(
      'name' => 'created_at',
      'type' => 'timestamp',
      'pk' => false,
      'allowNull' => true,
    ),
    'updated_at' => array(
      'name' => 'updated_at',
      'type' => 'timestamp',
      'pk' => false,
      'allowNull' => true,
    ),
  ),
  'pks' => array(),
  'uniques' => array(),
  'referencesTo' => array(),
  'referencesBy' => array(),
);