// Generated by CoffeeScript 1.9.1
(function() {
  var gulp;

  gulp = require('gulp');

  gulp.task('build', function() {
    return gulp.src(['bower_components/jquery/dist/jquery.js']).pipe(gulp.dest('public/vendor/jquery/'));
  });

}).call(this);
