<?php

define('KEY_PRIVATE', '-----BEGIN ENCRYPTED PRIVATE KEY-----
MIIBpjBABgkqhkiG9w0BBQ0wMzAbBgkqhkiG9w0BBQwwDgQIekqxvqnuV7ACAggA
MBQGCCqGSIb3DQMHBAh1sl2tCaoGSwSCAWCCdQiy8nizqgiGeRZr4cdakjzjjVLN
aRkrMJ1vmWxG6GoGJl4+VTGFnqM0r3pbhtk2Y3jgw9M01/jPjcLXYBIpY9XuoVjR
zwK4gA5H/MpuZA8FQ6oFvTpLdLvk3x134rMwGFSLbyjWLMHtJAKeZvnwlxyPCQJO
Nkp2smAFOpKizV8C2yvPoODLDueKHSehABCc/OViyxc4kgBkeWJDchtXl65Sfmsr
okdeU+msrpEDBF3mXlF39zfR6Ym7ZOvz272faGn0uRCr18hywYJclws2juakgBJM
zkDADuGjFZgrubtETk9Ts6Hr5SGPKuvoPBSxLMsS3b7SqGjYKagYlIBiluBgCHGx
3C1z/A25Mq014hSvCsAazNB/nkjSYOhm8WDDmVrkutn6qzVqr5fgPS8NGwrkwYI1
qFXvINKT+I6su21gMjPVYO0P47T95x0ToSpJgzu/9xMEWtQLDHMv6Yxm
-----END ENCRYPTED PRIVATE KEY-----');

define('KEY_PUBLIC', '-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMSJUyJaKD7dMj5Et5YgFAIbCBC1/RBE
vcfEdXvFR/uNjb/1EuQqH7PKClIi9qQs3N8i8pZW4g6Ixx31Ep702kMCAwEAAQ==
-----END PUBLIC KEY-----');

define('KEY_PASSPHRASE', 'komakai.menu');
